version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: ./target/cartoes-ms-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cartoes
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres@123
    depends_on:
      - postgres
      - kafka
    networks:
      - rede_local

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: cartoes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/db
      - ./initdb:/docker-entrypoint-initdb.d/:ro
    networks:
      - rede_local

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - rede_local

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - rede_local

networks:
  rede_local:
    driver: bridge

volumes:
  postgres_data: