version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: ./target/emissor-ms-0.0.1-SNAPSHOT.jar
    ports:
      - "8081:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:admin@mongo:27017/
    depends_on:
      - mongo
    networks:
      - cartoes-ms_rede_local

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data_emissor:/data/db
    networks:
      - cartoes-ms_rede_local

  mongo_express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8082:8081"
    depends_on:
      - mongo
    container_name: mongo_express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:admin@mongo:27017/
    networks:
      - cartoes-ms_rede_local

networks:
  cartoes-ms_rede_local:
    external: true

volumes:
  mongo_data_emissor: